# Generated by Django 4.2.3 on 2023-07-28 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_create_telegram_users_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('level_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_users.levelsenmodel')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
    ]
