# Generated by Django 4.2.3 on 2023-07-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_typewordsmodel_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsModel',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=128)),
                ('translation', models.JSONField()),
                ('type_word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.typewordsmodel')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'db_table': 'words',
            },
        ),
    ]
