# Generated by Django 4.2.3 on 2023-12-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_add_fields_time_sentences"),
    ]

    operations = [
        migrations.AddField(
            model_name="booksmodel",
            name="previous_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.booksmodel",
            ),
        ),
    ]
