# Generated by Django 4.2.3 on 2024-02-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_booksmodel_previous_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="TensesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("short_description", models.TextField()),
                ("full_description", models.TextField()),
                ("image_telegram_id", models.TextField()),
            ],
            options={
                "verbose_name": "tenses",
                "verbose_name_plural": "tenses",
                "db_table": "tenses",
            },
        ),
    ]
