# Generated by Django 4.2.3 on 2024-07-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_add_field_tenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordsmodel",
            name="transcription",
            field=models.CharField(default="ok", max_length=128),
            preserve_default=False,
        ),
    ]
