version: "3.9"
services:
  db:
    image: postgres:13.2
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
  bot:
    build: ./bot
    volumes:
      - ./bot:/app
    command: ["python", "-u", "./bot.py"]
    depends_on:
      - db
    env_file:
      - .env
  admin:
    build: ./admin
    volumes:
      - ./admin:/admin
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - admin
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  dbdata: