version: "3.9"

services:
  db_test:
    image: postgres:13.2
    env_file:
      - .env.test
    volumes:
      - dbdata:/var/lib/postgresql/data

  bot_test:
    build: ./bot
    volumes:
      - ./bot:/app
    command: ["pytest", "-v", "./tests"]  # Запуск тестов для bot
    env_file:
      - .env.test

  api_test:
    build: ./api
    ports:
      - 8002:80
    command: ["pytest", "-v", "./tests"]  # Запуск тестов для api
    depends_on:
      - db_test
    env_file:
      - .env.test
    volumes:
      - ./api:/app

  admin_panel_test:
    build: ./admin
    command: ["pytest", "-v", "./tests"]  # Запуск тестов для admin_panel
    ports:
      - 8003:80
    depends_on:
      - db_test
    env_file:
      - .env.test
    volumes:
      - ./admin:/app

volumes:
  dbdata: