from db.models.base import Base
from db.models.users import Users
from db.models.hero_levels import HeroLevels
from db.models.levels_en import LevelsEn
from db.models.users_referrals import UsersReferrals
from db.models.subscribes import Subscribes
from db.models.users_games_history import UsersGamesHistory
from db.models.games import Games
from db.models.main_languages import MainLanguages
from db.models.users_hero_levels_history import UsersHeroLevelsHistory
from db.models.charges import Charges
from db.models.users_charges_history import UsersChargesHistory
from db.models.books import Books
from db.models.users_books_history import UsersBooksHistory
from db.models.books_sentences import BooksSentences
from db.models.users_books_sentences_history import UsersBooksSentencesHistory
from db.models.grammar_exercises import GrammarExercises
from db.models.type_grammar_exercises import TypeGrammarExercises
from db.models.achievements import Achievements
from db.models.users_achievements_history import UsersAchievementsHistory
from db.models.users_grammar_exercises_history import UsersGrammarExercisesHistory
