from commands.registration import handle_registration
from commands.wait_name import handle_wait_name, handle_wait_name_incorrect_work, handle_wait_name_incorrect_work_buttons
from commands.wait_en_level import handle_wait_en_level, handle_wait_en_level_incorrect_work, handle_wait_en_level_incorrect_text_message
