# Generated by Django 4.2.3 on 2023-07-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroLevelsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('need_experience', models.BigIntegerField()),
                ('count_sentences', models.IntegerField()),
                ('count_games', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Hero level',
                'verbose_name_plural': 'Hero levels',
                'db_table': 'hero_levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LevelsEnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('A1', 'beginner'), ('A2', 'elementary'), ('B1', 'pre-intermediate'), ('B2', 'intermediate'), ('C1', 'upper-intermediate'), ('C2', 'advanced')], max_length=64)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'English level',
                'verbose_name_plural': 'English levels',
                'db_table': 'levels_en',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainLanguagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('russian', 'Русский язык')], max_length=64)),
            ],
            options={
                'verbose_name': 'Main language',
                'verbose_name_plural': 'Main languages',
                'db_table': 'main_languages',
            },
        ),
        migrations.CreateModel(
            name='TelegramUsersModel',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=64, null=True)),
                ('experience', models.BigIntegerField(default=0)),
                ('previous_stage', models.CharField(blank=True, max_length=64, null=True)),
                ('stage', models.CharField(blank=True, max_length=64, null=True)),
                ('hero_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_users.herolevelsmodel')),
                ('level_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_users.levelsenmodel')),
                ('main_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_users.mainlanguagesmodel')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
                'db_table': 'telegram_users',
            },
        ),
    ]
