from models.association_sentenses_words import sentence_word_association
from models.books import BooksModel
from models.books_sentences import BooksSentences
from models.english_levels import LevelsEn, LevelsEnModelDTO
from models.hero_level import HeroLevels
from models.main_language import MainLanguages, MainLanguagesModelDTO
from models.telegram_user import Users
from models.type_words import TypeWords
from models.users_books_history import UsersBooksHistory
from models.users_books_sentences_history import UsersBooksSentencesHistory
from models.users_hero_levels_history import UsersHeroLevelsHistory
from models.users_words_history import UsersWordsHistory
from models.words import Words

