from services.check_words import CheckWordsService
from services.learn_words import LearnWordsService
from services.read_sentence import ReadSentenceService
from services.registration import RegistrationService
from services.update_profile import UpdateProfileService
from services.wait_en_level import WaitEnLevelService
from services.wait_name import WaitNameService
from services.learn_words import LearnWordsService
