name: Run Black on Push

on:
  push:
    branches:
      - "**" 

jobs:
  run-black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Black
        run: |
          pip install black

      - name: Run Black with Line Length 120
        run: |
          black . --line-length 120
